server:
  port: 8080

spring:
  jpa:
    database-platform: com.jumiaproject.phonevalidator.sqlite.SQLDialect
    hibernate.ddl-auto: update
  datasource:
    url: jdbc:sqlite:src/main/resources/sample.db
    driver-class-name: org.sqlite.JDBC