server:
  port: 8080

spring:
  jpa:
    database-platform: com.jumiaproject.phonevalidator.sqlite.SQLDialect
    hibernate.ddl-auto: update
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:${DB_PATH}